### ISSUE TITLE
Temperature child devices

### ISSUE THREAD

**Issue by jhattonc** [reneboer/vera-TeslaCar#2]
![059EB36D-1CF6-4ADE-A847-B8590BA365F4](https://user-images.githubusercontent.com/60494433/76146332-c3b80c80-605f-11ea-8a62-3bce0328765f.png)
All child devices displaying interior or exterior are showing degrees F but clearly displaying degrees C shows 0 F when actually is 32 F

**Comment by reneboer** [comment]
It seems the car always reports in Celsius even when the GUI settings are for Fahrenheit. And speed and distance always in miles, but that is documented. Nice and consistent system use (not). I'll fix that in a next release.

**Comment by reneboer** [comment]
Hi, can you try V1.8. Upload the L_TeslaCar1.lua and I_TeslaCar1.xml and let me know. It should use the temp unit settings of your Vera/openLuup now.

BTW, I do assume your Tesla temp units are set for Fahrenheit too right? In the plugin this is captured in the variable GuiTempUnits. Please confirm this is set to F in your case.

**Comment by reneboer** [comment]
Assuming fixed.
