### ISSUE TITLE
Mileage Spelling and Factor Incorrect

### ISSUE THREAD

**Issue by guerinwoodgate** [reneboer/vera-TeslaCar#3]
On the Status tab, mileage is spelled milage.  Also, my car is reporting the mileage in miles but depicts a factor of Km which is wrong.

**Comment by reneboer** [comment]
Hi @guerinwoodgate ,

Can you tell me the values of the GuiChargeRateUnits and GuiDistanceUnits variables in the Tesla plugin?

**Comment by guerinwoodgate** [comment]
Here are the values:

GuiChargeRateUnits - kW

GuiDistanceUnits - mi/hr

 

The problem that I am trying to solve is in the screenshot below.  The mileage value is displayed as Km instead of miles.

**Comment by reneboer** [comment]
Hi @guerinwoodgate ,

Just posted new J_TestCar1.js and L_TeslaCar.lua files that should fix this. Can you have a try?

**Comment by reneboer** [comment]
No feedback, assume fixed. Closing issue.
