### ISSUE TITLE
Random Heat or AC Issue

### ISSUE THREAD

**Issue by guerinwoodgate** [reneboer/vera-TeslaCar#4]
When creating a scene and turning on the climate control, sometimes I get AC with no change in the temperature, or I get heat on 'Hi' setting (highest temperature).  I am unable to determine why my requested temperature is ignore when AC is turned on, nor determine what is causing the random toggle between AC and Heat.

The climate control does have an on/off switch that is labeled heat that might need to be updated as well.

**Comment by reneboer** [comment]
The working of the AC is a bit of a mystery. Also if you turn the climate off it remains completely off when you get in the car and drive away.
Have you tried the same scenario via the tesla app and did that give a different result?

**Comment by reneboer** [comment]
No updates so assuming all is ok. Closing issue.
