### ISSUE TITLE
Support for Tesla accounts w/ MFA enabled

### ISSUE THREAD

**Issue by jsamuel1** [reneboer/vera-TeslaCar#7]
Tesla accounts with MFA enabled can't login.

To see an example of the MFA login with the new OAuth2 endpoint, see here:
https://github.com/timdorr/tesla-api/issues/215#issuecomment-770218585

This may need an initial oath login with MFA code challenge, and only storing the OAuth codes after that -- any relogin with uid/pwd will require a new 2FA challenge.

**Comment by reneboer** [comment]
I will look at this some time in the future, but I do not have the time now.

**Comment by 3rdStng** [comment]
> I will look at this some time in the future, but I do not have the time now.

Any chance you can look into this? I just installed the app on my Vera and can't get past the invalid login id errors. I'm 99% sure it is related to the MFA on my account.

**Comment by reneboer** [comment]
Addressed using third party tool for authentication and using the refresh key for authentication in the app.
