### ISSUE TITLE
LocationHome - 0 = car not at home (Vera) location, 1 = at home location <---how is this set?

### ISSUE THREAD

**Issue by sTevefor3** [reneboer/vera-TeslaCar#8]
Vera shows that I am home, based upon my iPhone location.  My Tesla is home, too, sitting in my driveway.
However, TeslaCar Status shows "Car location Away", with my home's Lat/Lon.

How do I fix this?  I can manually change the location settings in TeslaCar, but the next refresh switches it back.

**Comment by PablaV** [comment]
Have you checked that your Vera has the correct coordinates for your home in its settings? I had the same issue until I updated my home coordinates in Vera

**Comment by sTevefor3** [comment]
> Have you checked that your Vera has the correct coordinates for your home in its settings? I had the same issue until I updated my home coordinates in Vera

Thanks for the prompt reply, PablaV.
That was the answer.

I found 3 different GPS coordinates for my home location; that is to say, 3 of my computers use slightly different coordinates.  I matched the TeslaCar coords with Vera's just now.  So far, TeslaCar has been showing "Car location | Home" for the last 10 min.  Maybe I fixed it.

Thanks, again!

**Comment by sTevefor3** [comment]
> Have you checked that your Vera has the correct coordinates for your home in its settings? I had the same issue until I updated my home coordinates in Vera

Well, damn.  I checked last night while at home, and TeslaCar and Vera showed different Lat/Long values, thus TeslaCar thinks I'm "away"...even though the lat/long values are really quite close.

Today, I'm at work, and TeslaCar's Lat/Long has changed appropriately showing my work location's correct lat/long and displaying "away" on the status page.

When I'm at home, TeslaCar shows my home lat/long but still shows "away".  I'm afraid I don't understand how to fix this.

**Comment by reneboer** [comment]
You have to enter the exact latitude and longitude of your home in the Vera location settings. If your car is not parked next to your house, you can enter that as location.
